### ISSUE TITLE
How do I edit the LAYOUT of a existing component in ArkhamHorror 2ndEd? 

### ISSUE THREAD

**Issue by TragicTheBlathering** [CGJennings/strange-eons#50]
Sorry if this is not the place to ask, but I can not find any forums or anywhere to ask about how to use this app... I'm trying to make some cards using the Arkham Horror 2ndED plug in but having some issues working out how to use it.

![Clipboard-1](https://user-images.githubusercontent.com/3701509/163920798-6e41e872-8eca-4ea4-9cca-128a8f87a85c.jpg)

This is the SKILL card form the plugin... but how can I edit the layout? I would like to move the expantion symbol UP so it is off the frame and also edit the text box so it starts drawing text closer to the top of the card? But i can not find anyway to edit the card layout.. I can only edit the input field "NAME" and "EFFECT"?

![Clipboard-3](https://user-images.githubusercontent.com/3701509/163921059-ab4ec36d-ee39-4857-8b86-d7e1b8e3ddc8.jpg)

Any help would be really appreciated! Thanks! 

And if there is a forum or reddit or something for this app, please post a link!

**Comment by CGJennings** [comment]
The general philosophy of Strange Eons is to separate the graphic design/layout of game components from the process of creating the cards themselves. Card layouts generally follow those of official designs. That said, it is generally possible to adjust at least some aspects of most card types.

Here is one example that uses the most common approach:

1.  Install the **Developer Tools** plug-in.
2.  Make sure **View/Region Boxes** is enabled. This is not strictly required, but makes the modification process easier.
3.  Create/open the card you want to modify (in these instructions, an AH Skill).
4.  Choose **Window/Setting Explorer**.
5.  In the text field marked Regex setting filter, type (for example) `skill.*region`. This will narrow down the list of visible settings to those that start with `skill` and end with `setting`.
6.  Double click the value of a setting you wish to modify and enter a new value. Regions describe a rectangular area using the x- and y-coordinate of the upper-left corner, the width, and the height. For example, if you change `skill-text-region` from 21,122,200,210 to 21,112,200,220 then the top of the "effects" text area will move up while the bottom stays in the same location (since the height was increased accordingly).
7.  To modify the location of expansion symbols, change the filter to `expsym`. There will be one main setting key, and (in this case of skill cards) some additional entries for specific expansions. Changing these to 112,90,21,22 will move the symbol above the effect text without changing the size.
8.  Skill cards define a "page shape" to create a small cutout from the bottom the text area for certain expansion symbols. These are rarely used, and moreover do not always have accessible settings you can modify. In this case, though, it is. Type `shape` in the filter field and locate `skill-text-shape`. Changing this to 0,0,350,0,0 will effectively remove the cutout by changing its size to 0 and causing it to start below the bottom of the text area.

In the end you should have something like this:

![skill-edit-example](https://user-images.githubusercontent.com/25697451/164391252-3731dd4c-3614-47fc-bc82-8c6244ba9df4.png)

Note that these changes will only affect the card that they are applied to. New skill cards will follow the standard layout unless similarly modified. However, you can easily clone the modified card by choosing **Edit/Spin Off**.

This only scratches the surface of possible modifications, but it should get you started.

The [developer manual](http://se3docs.cgjennings.ca/dm-index.html) and [plug-in authoring kit](http://se3docs.cgjennings.ca/dm-pak.html) will contain additional information and examples that may be useful. You may have to hunt around, though, since their primary purpose is creating new designs rather than hacking existing ones!

Asking here is fine, though generally this is meant for reporting bugs or for plug-in developers to ask questions/request features needed by plug-ins. It would make more sense to ask in the [documentation repository](https://github.com/CGJennings/se3docs) or using the [Contact link on my site](https://cgjennings.ca/contact/) (which I think you also did).

Have fun!

**Comment by TragicTheBlathering** [comment]
Thanks so much for the reply. I'm sorry for contacting you at two locations but I was unsure what would be the best option. 

You wouldn't have a developer pack containing all the required fonts for Arkham Horror (I guess I need to call it 2nd Ed now!). In my case it may be easier for me to build a black card in your app and then apply the text myself in affinity designer or something. But I'd need the font pack (Windows compatible) 

Also as I'm already bothering you.. Is there a github with more game repositories besides the ones in the default plugin list? I was surprised to see no eldritch horror or AH3 or some other games. I thought maybe there was another listing of more plugs...maybe not 100% vetted by you or whatever? 

Thanks again for your reply and for strange eons. AH modding might not be what it was but I still enjoy it lol 

Tragic 

*** Sent from my phone. Sorry for the brevity. ***
________________________________

**Comment by CGJennings** [comment]
No problem, glad I could help!

You can get the fonts fairly easily from the plug-in itself. Open the plug-in manager (**Toolbox/Manage Plug-ins**) and choose **Open Plug-in Folder**. Find the main AH plug-in, select it and choose **Copy**. Then go back to Strange Eons, and paste the file into a project. Right click and choose **Import Plug-in** to convert the plug-in into a regular folder. You'll find the fonts inside.

There are some GitHub repositories for individual plug-ins that I know of, though the ones I know of are listed in the catalogue. There are some plug-ins floating around (not on GitHub so far as I know) that have never been submitted for inclusion in the catalog. For example, sometimes people post plug-ins directly to a forum.

I think I heard from someone who was interested in making an Eldritch Horror plug-in, but I don't know what the status of the project is.
