### ISSUE TITLE
Font Outline / Shadow

### ISSUE THREAD

**Issue by Matoneto** [CGJennings/strange-eons#73]
Strange Eons seems to be a great software to make cards and I have a question regarding fonts. Is it possible for a font to have a shadow / outline / stroke effect? This is often useful to be able to read text over a background of similar color.

**Comment by CGJennings** [comment]
The short answer is yes, it is possible.

In general: Use the font object to get a glyph vector for the target string. The glyph vector gives you a shape (outline) for each character. You can do all sorts of things with the mask, such as fill it in with solid colour or a pattern (Paint), stroke the outline (optionally with dashed lines, etc.). To create outlined text you would typically stroke the outside of the shape (the character outline) and fill the interior.

If you don't want to create the glyph vector yourself, there is a class `ca.cgjennings.graphics.strokes.TextStroke` that could probably be used to do most of the work for you. It does a slightly more involved job: making some text follow a path (such as a curve). It provides a single shape that combines all of the individual characters. You should be able to pass it a straight line instead of a curve.

All of this assumes that your text is a simple string, like a title or label. If your text is markup (lines or paragraphs of text that the user can style), I believe the needed information is created, but it isn't currently exposed by the MarkupRenderer class.

Alternatively, you can cheat. You could draw the text multiple times in the stroke colour, at slight offsets from the true position [such as (-1,-1), (1,-1), (-1,1), (1,1)]. Depending on your needs, that may suffice.

**Comment by Matoneto** [comment]
Thanks for this implementation guide. I was looking around in the manuals and API documentations but couldn't find an easy way to do this.

**Comment by Matoneto** [comment]
Thanks for this much feedback. I am still new to Strange Eons and still learning the program.

**Comment by CGJennings** [comment]
No problem! I'll close this issue.
